### PR TITLE
Added support for the debug flag

### PR DESCRIPTION
**Pull request by JordyMoos**
Also upgraded the tests for elm 0.18.0

### CODE REVIEW

**Comment by JordyMoos** [comment]
I suggest to bump this to a new major version @rtfeldman

**Comment by rtfeldman** [comment]
Nice, thank you @JordyMoos!

**Comment by rtfeldman** [comment]
Published as 2.0.0 - thanks @JordyMoos!

**Comment by JordyMoos** [comment]
You're welcome @rtfeldman

**Pull request merged**
